stages:

  * test
  * build
  * docker

variables:
MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
paths:
  - .m2/repository

test:
stage: test
image: maven:3.9.6-eclipse-temurin-17
script:
  - mvn clean test

build:
stage: build
image: maven:3.9.6-eclipse-temurin-17
script:
  - mvn clean package -DskipTests
artifacts:
paths:
  - target/*.jar

docker:
stage: docker
image: docker:latest
services:
  - docker:dind
dependencies:
  - build
script:
  - docker login u korkabal -p passer
  - docker build -t korkabal/task-api .
  - docker push korkabal/task-api
only:
  - develop
